-- DROP-CREATEにて、DB及びユーザを作り直せるようにする
DROP DATABASE IF EXISTS NEXTGENDB;
CREATE DATABASE NEXTGENDB;
USE NEXTGENDB;
-- SHOW DATABASES;
DROP USER IF EXISTS nextgenuser;
CREATE USER 'nextgenuser'@'%' IDENTIFIED BY '12345';
GRANT ALL ON NEXTGENDB.* TO 'nextgenuser'@'%';
-- SELECT USER, HOST FROM mysql.user;
