-- DROP-CREATEにて、テーブル構成を作り直せるようにする
USE NEXTGENDB;

-- テーブルDROPのSQL
DROP TABLE IF EXISTS SEAT;

-- テーブルCREATEのSQL
CREATE TABLE SEAT(
	ID INT AUTO_INCREMENT,
	STAND VARCHAR(256),
	EVENT VARCHAR(256),
	`TYPE` VARCHAR(256),
	POSITION VARCHAR(256),
	PLACE VARCHAR(256),
	IS_DELETED VARCHAR(1) DEFAULT '0',
	CREATED_BY VARCHAR(256) DEFAULT 'dbadmin',
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY VARCHAR(256) DEFAULT 'dbadmin',
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
);

-- SHOW TABLES;
